import AttributeIcons from 'components/Icons/AttributeIcons'

const ATTRIBUTES = {
  string: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'String',
      valueType: 'text',
      description: 'string',
      inputWidget: 'Input',
      inputWidgetType: 'text',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'string',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },

  text: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Text',
      valueType: 'textarea',
      description: 'text',
      inputWidget: 'Textarea',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'text',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  password: {
    info: {
      icon: AttributeIcons.IconPassword,
      label: 'Password',
      valueType: 'password',
      description: 'password',
      inputWidget: 'Input',
      inputWidgetType: 'password',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'password',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  email: {
    info: {
      icon: AttributeIcons.IconEmail,
      label: 'Email',
      valueType: 'email',
      description: 'email',
      inputWidget: 'Input',
      inputWidgetType: 'email',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'email',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  integer: {
    info: {
      icon: AttributeIcons.IconNumber,
      label: 'Integer',
      valueType: 'number',
      description: 'integer',
      inputWidget: 'Input',
      inputWidgetType: 'number',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'integer',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  biginteger: {
    info: {
      icon: AttributeIcons.IconNumber,
      label: 'Biginteger',
      valueType: 'number',
      description: 'biginteger',
      inputWidget: 'Input',
      inputWidgetType: 'number',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'biginteger',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  float: {
    info: {
      icon: AttributeIcons.IconNumber,
      label: 'Float',
      valueType: 'number',
      description: 'float',
      inputWidget: 'Input',
      inputWidgetType: 'number',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'float',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  decimal: {
    info: {
      icon: AttributeIcons.IconNumber,
      label: 'Decimal',
      valueType: 'number',
      description: 'decimal',
      inputWidget: 'Input',
      inputWidgetType: 'number',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'decimal',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  date: {
    info: {
      icon: AttributeIcons.IconDatetime,
      label: 'Date',
      valueType: 'date',
      description: 'date',
      inputWidget: 'Input',
      inputWidgetType: 'date',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'date',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  time: {
    info: {
      icon: AttributeIcons.IconDatetime,
      label: 'Time',
      valueType: 'time',
      description: 'time',
      inputWidget: 'Input',
      inputWidgetType: 'time',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'time',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  datetime: {
    info: {
      icon: AttributeIcons.IconDatetime,
      label: 'Datetime',
      valueType: 'datetime',
      description: 'datetime',
      inputWidget: 'Input',
      inputWidgetType: 'datetime-local',
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'datetime',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  json: {
    info: {
      icon: AttributeIcons.IconJson,
      label: 'Json',
      valueType: 'json',
      description: 'json',
      inputWidget: 'Json',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'json',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  enum: {
    info: {
      icon: AttributeIcons.IconEnum,
      label: 'Enum',
      valueType: 'enum',
      description: 'enum',
      inputWidget: 'Enum',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'enum',
      columnName: '',
      displayName: '',
      enum: [],
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  boolean: {
    info: {
      icon: AttributeIcons.IconBoolean,
      label: 'Boolean',
      valueType: 'boolean',
      description: 'boolean',
      inputWidget: 'Boolean',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'boolean',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  file: {
    info: {
      icon: AttributeIcons.IconFile,
      label: 'File',
      valueType: 'string',
      description: 'file',
      inputWidget: 'File',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'file',
      columnName: '',
      displayName: '',
      required: false,
      private: false,
    },
  },
  relation: {
    info: {
      icon: AttributeIcons.IconRelation,
      label: 'Relation',
      valueType: 'relation',
      description: 'Relation',
      inputWidget: 'Relation',
      inputWidgetType: null,
      layout: { width: 'w-1/2' },
    },
    model: {
      type: 'relation',
      columnName: '',
      displayName: '',
      relation: 'oneToOne',
      association: 'hasOne',
      reference: '',
      referenceColumnName: '',
      referenceDisplayName: '',
    },
  },
}

export { ATTRIBUTES }
