import AttributeIcons from './AttributeIcons'

const ATTRIBUTES = {
  string: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'String',
      valueType: 'text',
      description: 'string',
      inputWidget: 'Input',
      inputWidgetType: 'text',
    },
    model: {
      type: 'string',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },

  text: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Text',
      valueType: 'textarea',
      description: 'text',
      inputWidget: 'Textarea',
      inputWidgetType: null,
    },
    model: {
      type: 'text',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  // richtext: {
  //   info: {
  //     icon: AttributeIcons.IconText,
  //     label: 'Richtext',
  //     valueType: 'text',
  //     description: 'richtext',
  //     inputWidget: '',
  //     inputWidgetType: '',
  //   },
  //   model: {
  //     type: 'richtext',
  //     columnName: '',
  //     displayName: '',
  //     defaultValue: null,
  //     required: false,
  //     unique: false,
  //     private: false,
  //     configurable: true,
  //   },
  // },
  password: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Password',
      valueType: 'password',
      description: 'password',
      inputWidget: 'Input',
      inputWidgetType: 'password',
    },
    model: {
      type: 'password',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  email: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Email',
      valueType: 'email',
      description: 'email',
      inputWidget: 'Input',
      inputWidgetType: 'email',
    },
    model: {
      type: 'email',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  integer: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Integer',
      valueType: 'number',
      description: 'integer',
      inputWidget: 'Input',
      inputWidgetType: 'number',
    },
    model: {
      type: 'integer',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  biginteger: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Biginteger',
      valueType: 'number',
      description: 'biginteger',
      inputWidget: 'Input',
      inputWidgetType: 'number',
    },
    model: {
      type: 'biginteger',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  float: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Float',
      valueType: 'number',
      description: 'float',
      inputWidget: 'Input',
      inputWidgetType: 'number',
    },
    model: {
      type: 'float',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  decimal: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Decimal',
      valueType: 'number',
      description: 'decimal',
      inputWidget: 'Input',
      inputWidgetType: 'number',
    },
    model: {
      type: 'decimal',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  date: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Date',
      valueType: 'date',
      description: 'date',
      inputWidget: 'Input',
      inputWidgetType: 'date',
    },
    model: {
      type: 'date',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  time: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Time',
      valueType: 'time',
      description: 'time',
      inputWidget: 'Input',
      inputWidgetType: 'time',
    },
    model: {
      type: 'time',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  datetime: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Datetime',
      valueType: 'datetime',
      description: 'datetime',
      inputWidget: 'Input',
      inputWidgetType: 'datetime-local',
    },
    model: {
      type: 'datetime',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      unique: false,
      private: false,
    },
  },
  json: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Json',
      valueType: 'json',
      description: 'json',
      inputWidget: 'Json',
      inputWidgetType: null,
    },
    model: {
      type: 'json',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  enum: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Enum',
      valueType: 'enum',
      description: 'enum',
      inputWidget: 'Enum',
      inputWidgetType: null,
    },
    model: {
      type: 'enum',
      columnName: '',
      displayName: '',
      enum: [],
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  boolean: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Boolean',
      valueType: 'boolean',
      description: 'boolean',
      inputWidget: 'Boolean',
      inputWidgetType: null,
    },
    model: {
      type: 'boolean',
      columnName: '',
      displayName: '',
      defaultValue: null,
      required: false,
      private: false,
    },
  },
  relation: {
    info: {
      icon: AttributeIcons.IconText,
      label: 'Relation',
      valueType: 'relation',
      description: 'Relation',
      inputWidget: 'Relation',
      inputWidgetType: null,
    },
    model: {
      type: 'relation',
      columnName: '',
      displayName: '',
      private: false,
    },
  },
}

export { ATTRIBUTES }
